
### This script is designed to proccess a genetic query dataframe, generated by an SQL query, and then return either 1) df of SNP statistics or 2) the actual genetic data for the queried SNPs (including missing/invalid base pairs).
import re
import pandas as pd

def clean_genetic_query(query_df: pd.DataFrame, snp_list: list) -> pd.DataFrame:

    if query_df is None or query_df.empty:
        return query_df

    exact_mask = query_df['manifest_name'].isin(snp_list)

    possible_mask = query_df['possible_rsids'].apply(
        lambda x: any(snp in str(x).split(';') for snp in snp_list)
    )

    probable_mask = possible_mask & ~exact_mask

    query_df = query_df.copy()
    query_df['match_type'] = 'exact'
    query_df.loc[probable_mask, 'match_type'] = 'probable'

    def pick_matching_snp(possible_rsids):
        for snp in str(possible_rsids).split(';'):
            if snp in snp_list:
                return snp
        return None  
    
    query_df.loc[probable_mask, 'manifest_name'] = (
        query_df.loc[probable_mask, 'possible_rsids'].apply(pick_matching_snp)
    )

    query_df = query_df.rename(columns={'manifest_name': 'rsid'})
    query_df = query_df.drop(columns=['nucleotides', 'prefix', 'possible_rsids'])

    query_df = query_df.set_index('rsid').T
    query_df = query_df.reset_index().rename(columns={'index': 'pid'})

    match_types = query_df.loc[query_df['pid'] == 'match_type'].iloc[0].to_dict()

    query_df = query_df[query_df['pid'] != 'match_type']

    return query_df, match_types


#function to be applied over genotype reads
def is_valid_genotype(geno: str) -> bool:

    valid_genotype_pattern = re.compile(r'^[AGCT]{2}$')

    return bool(valid_genotype_pattern.match(str(geno)))

#Function to count alleles for a given SNPs genotypes, applied to a single SNP (column)
def count_alleles(series: pd.Series):
    counts = {}
    for geno in series.dropna():
        if is_valid_genotype(geno):
            for allele in geno:
                counts[allele] = counts.get(allele, 0) + 1
    return counts

#Function to generate SNP stats for a single SNP (colulmn)
def calculate_snp_stats(series: pd.Series, rsid: str) -> dict:

    series = series.dropna().astype(str)
    valid_mask = series.apply(is_valid_genotype)
    series = series[valid_mask]
    sample_size = len(series)

    #allele counts
    allele_counts = count_alleles(series)
    alleles = list(allele_counts.keys())

    if len(alleles) == 1:  
        allele1 = alleles[0]
        sample_size = len(series)
        pool = sample_size * 2
        freq1 = allele_counts[allele1] / pool
        
        return {
            "rsid": rsid,
            "allele1": f"{allele1} ({freq1:.3f})",
            "allele2": "/",  
            "sample_size": sample_size,
            "hmz_maj": f"{allele1}{allele1} (1.0)",  #everyone is homozygous
            "htz": "NA",
            "hmz_min": "NA",
            "maf": "0.0"
        }
    
    if len(alleles) != 2:  #tri-allelic etc.
        return None

    #two alleles → calculate frequencies
    allele1, allele2 = alleles
    pool = sample_size * 2
    freq1 = allele_counts[allele1] / pool
    freq2 = allele_counts[allele2] / pool

    major, minor = (allele1, allele2) if freq1 >= freq2 else (allele2, allele1)

    #genotype counts
    hmz_maj = (series == major + major).mean()
    htz = ((series == major + minor) | (series == minor + major)).mean()
    hmz_min = (series == minor + minor).mean()

    return {
        "rsid": rsid,
        "allele1": f"{allele1} ({freq1:.3f})",
        "allele2": f"{allele2} ({freq2:.3f})",
        "sample_size": sample_size,
        "hmz_maj": f"{allele1}{allele1} ({hmz_maj:.3f})",
        "htz": f"{allele1}{allele2} ({htz:.3f})",
        "hmz_min": f"{allele2}{allele2} ({hmz_min:.3f})",
        "maf": round(min(freq1, freq2), 3)
    }

#Function to apply calculate_snp_stats to adult and child cohorts
def cohort_snp_stats(df: pd.DataFrame, rsids: list) -> pd.DataFrame:
    rows = []
    for rsid in rsids:
        stats = calculate_snp_stats(df[rsid], rsid)
        if stats:
            rows.append(stats)
    return pd.DataFrame(rows)

def add_warnings(stats_df: pd.DataFrame) -> pd.DataFrame:

    stats_df["maf"] = pd.to_numeric(stats_df["maf"], errors="coerce")
    
    stats_df["criteria_warning"] = ""
    stats_df.loc[stats_df["allele2"] == "/", "criteria_warning"] = "mono-allelic"
    stats_df.loc[(stats_df["maf"] < 0.05) & (stats_df["allele2"] != "/"), "criteria_warning"] = "low_maf"
    return stats_df

#function that will return sample size counts of participants with complete records across all SNPs queried.
def complete_record_count(adult_df: pd.DataFrame, child_df: pd.DataFrame, snp_list: list) -> dict:
    """
    Count participants with complete records across all SNPs in snp_list.
    Returns dict with counts for adults, children, and total.
    """
    def valid_subset(df):
        
        sub_df = df[snp_list]

        sub_df = sub_df.dropna()
        
        mask = sub_df.map(is_valid_genotype).all(axis=1)

        return sub_df[mask]

    adult_genetic = valid_subset(adult_df)
    child_genetic = valid_subset(child_df)

    counts = {
        "total": len(adult_genetic) + len(child_genetic),
        "adults": len(adult_genetic),
        "children": len(child_genetic),
    }

    return counts
